In [1]:
import numpy as np

In [11]:
list_1 = list(range(10))

arr_1 = np.array(list_1)

print(arr_1)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
arr_1[2:5]

array([2, 3, 4])

In [14]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


arr_2d[1, 1] # Ans: 5

np.int64(5)

In [15]:
arr_2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [18]:
arr_2d[1:, 1:]

array([[5, 6],
       [8, 9]])

In [19]:
arr_2d[:, 2]

array([3, 6, 9])

In [24]:
arr_2d[0, :]

array([1, 2, 3])

## Boolean Masking

In [26]:
arr = np.array([10, 15, 20, 30, 35, 40, 41, 43, 50])

print(arr)

[10 15 20 30 35 40 41 43 50]


In [31]:
mask = arr > 30

In [32]:
arr[mask]

array([35, 40, 41, 43, 50])

In [35]:
arr[arr % 5 != 0]

array([41, 43])

### Question:

```python
arr = np.array([10, 15, 20, 30, 35, 40, 41, 43, 50])
```

Filter only the even numbers from the above numpy array.

In [36]:
arr[arr % 2 == 0]

array([10, 20, 30, 40, 50])

In [37]:
arr[(arr > 15) & (arr < 40)]

array([20, 30, 35])

In [53]:
# Variation for Data Analysis: Filtering rows based on column values
sales_data = np.array([
    [101, 50, 200],  # ID, Units Sold, Price
    [102, 10, 50],
    [103, 75, 300],
    [104, 20, 100],
    [105, 60, 250]
])

In [58]:
sales_data[[2, 4], 0]

array([103, 105])

In [52]:
sales_data[:, 1]

array([50, 10, 75, 20, 60])

In [42]:
total_sales = sales_data[:, 2] * sales_data[:, 1]
print(total_sales)

[10000   500 22500  2000 15000]


In [49]:
# Price less than or equals to 100
sales_data[sales_data[:, 2] <= 100]

array([[102,  10,  50],
       [104,  20, 100]])

In [51]:
total = total_sales.sum()
print(total)

50000


## Transpose

In [59]:
print(sales_data)

[[101  50 200]
 [102  10  50]
 [103  75 300]
 [104  20 100]
 [105  60 250]]


In [60]:
sales_data.T

array([[101, 102, 103, 104, 105],
       [ 50,  10,  75,  20,  60],
       [200,  50, 300, 100, 250]])

### Question

```python
sales_data = np.array([
    [101, 50, 200],  # ID, Units Sold, Price
    [102, 10, 50],
    [103, 75, 300],
    [104, 20, 100],
    [105, 60, 250]
])
```

1. From the above sales data, find the total units sold.
2. Also, find the average price

In [62]:
sales_data[:, 1].sum()

np.int64(215)

In [63]:
sales_data[:, 2].mean()
 

np.float64(180.0)